# mkdir -p /root/docker/npm/
# cd /root/docker/npm/
# docker compose up -d
version: '3'
services:
  app:
    image: 'chishin/nginx-proxy-manager-zh:release'
    restart: always
    ports:
      - '8880:80'
      - '81:81'
      - '8443:443'
    volumes:
      - /root/docker/npm/data:/data
      - /root/docker/npm/letsencrypt:/etc/letsencrypt